### ISSUE TITLE
Variant Page

### ISSUE THREAD

**Issue by onursumer** [knowledgesystems/msk-insight#46]
The Variant page will help researchers and clinicians interpret individual germline variants in cancer patients. Users will be able to search variants by genomic, coding or protein changes based on HGVS (Human Genome Variation Society) Nomenclature. The following information will be included: 

- [ ] Variant effect annotation via VEP
- [ ] Pathogenicity assessment and penetrance stratification via methodology by Srinivasan et al.
- [ ] Overall prevalence across cancer types
- [ ] Prevalence in each cancer type
- [ ] Prevalence in somatic-germline interplay (biallelic inactivation)
- [ ] A mutational lollipop diagram highlighting the current variant as well as linking to other variants in the same gene
- [ ] Race, gender and age distribution
- [ ] Links to gnomAD, dbSNP, and ClinVar.
